POST https://asm03-nodejs-server.onrender.com/user/signup
Content-Type: application/json


{
    "fullname": "Phạm Thắng",
    "email": "test@example.com",
    "password": "123456",
    "phone": "123456789",
    "_csrf": "S7cJn9Eb-HYjsW70gNlU9VVUixhc7rCWaRZc"
}

###############
GET https://asm03-nodejs-server.onrender.com/admin/some-route
################################
POST https://asm03-nodejs-server.onrender.com/shop/login
Content-Type: application/json


{
    "email": "caoboi520@gmail.com",
    "password": "123123123",
    "_csrf": "6FuyUsxg-Pf2d4pivQQS5geCYyCWPVHgmHyo"
}
################################################################
GET https://asm03-nodejs-server.onrender.com/shop/logout


########
GET  https://asm03-nodejs-server.onrender.com/shop/all-product
##########
GET  https://asm03-nodejs-server.onrender.com/shop/cart

########
GET  https://asm03-nodejs-server.onrender.com/shop/order
###########
POST  https://asm03-nodejs-server.onrender.com/shop/order-detail
Content-Type: application/json


{
    "OrderId": "65ef215d222c8fabf4fb26d0"
}

#############
GET  https://asm03-nodejs-server.onrender.com/admin/all-room